### ISSUE TITLE
build file references incorrect path

### ISSUE THREAD

**Issue by royrusso** [masda70/relasticsearch#1]
The FQN to the main class may be incorrect in the build file. Under build.sbt, it references:

`mainClass in Compile := Some("com.masda70.relasticsearch.ReIndexer")`

It should be:

`mainClass in Compile := Some("com.masda70.relasticsearch.Indexer")`

I'm looking at the master branch, so things may have changed in develop.

**Comment by masda70** [comment]
Yes indeed it's been fixed in develop, as well as many other things. I will push a release.

**Comment by masda70** [comment]
Done.
